### ISSUE TITLE
Finish Locust Example

### ISSUE THREAD

**Issue by sergioarmgpl** [sergioarmgpl/operating-systems-usac-course#6]
Finish the page explain how locust work and some basic examples about that

**Comment by jossiebk** [comment]
@sergioarmgpl , I'd like to do this one, i already have a usefull example of a locust API on Python with  Json test file to any ip server, does it count for this issue?

**Comment by sergioarmgpl** [comment]
You are assigned right now @jossiebk

**Comment by sergioarmgpl** [comment]
Done
